import AppHeading from "src/components/AppHeading";
import "src/styles/globals.css";

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>RSC POC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex min-h-screen flex-col items-center justify-center bg-[#2e026d] bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <main className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <AppHeading />
          {children}
        </main>
      </body>
    </html>
  );
}
